package com.etz.fraudeagleeyemanager.enums;

public enum FraudRedisKey {
    POCKETMONI, MOBILEGATE, CORPORATEPAY, SWITCHIT, ACCOUNTPRODUCT, ACCOUNT, CARDPRODUCT,
    CARD, EMAILGROUP, INTERNALWATCHLIST, OFACWATCHLIST, PARAMETER, PRODUCTDATASET, PRODUCT,
    PRODUCTRULE, REPORT, REPORTSCHEDULER, RULE, TRANSACTIONLOG, NOTIFICATIONGROUP, PRODUCTSERVICE
}
