stages:
  - build
  - test

build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - echo build/codeoptimus1.txt
    artifacts:
        paths:
            - build/
        
test:
   stage: test
   script:
       - echo "Testing"
       - if exist build\codeoptimus1.txt ( echo "File exists") 