include: 'https://raw.githubusercontent.com/checkmarx-ltd/cx-flow/master/templates/gitlab/v2/Checkmarx.gitlab-ci.yml'

stages:
  - build

build:
    stage: build
    script:
        - echo "Building"
        - echo "$CHECKMARX_USERNAME"
        - mkdir build
        - echo build/codeoptimus1.txt
    artifacts:
        paths:
            - build/