include: '.checkmarx.yml'

stages:
  - test

build:
    stage: test
    script:
        - echo "Checmarx Scanning Begins"
        - mkdir build
        - echo build/codeoptimus1.txt
    artifacts:
        paths:
            - build/