stages:
  - checkmarx

checkmarx:
    stage: checkmarx
    script:
        - echo "Checkmarx Scan Begins"
        - mkdir build
        - echo build/codeoptimus1.txt
    artifacts:
        paths:
            - build/