stages:
  - build
  - test

build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - echo build/codeoptimus1.txt
    artifacts:
        paths:
            - build/
        
test:
   stage: test
   script:
       - echo "Testing"
       - test -f "build/codeoptimus1.txt"