stages:
  - build

build:
    stage: build
    script:
        - echo "Building"
        - echo "$CHECKMARX_USERNAME"
        - mkdir build
        - echo build/codeoptimus1.txt
    artifacts:
        paths:
            - build/