
server:
  port: 9190
  servlet:
    context-path: /api

kafka:
  pocketmoni:
    topic: fraud-pocketmoni

  mobilegate:
    topic: fraud-mobilegate

  corporate:
    topic: fraud-corporatepay

  switchit:
    topic: fraud-switchit

security:
  oauth2:
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhYcaMfySijW5QEGsJwVtiQrU2EIqcGWShtOow7WR9Y8XB+gHcvMs3/oLieyRYXaEUuwtSGSPzUG5vW5q5BVYNjnM6u+ZAhRHxTYoBiwOGXf/jOB39wraZRk4Vuz2GErHXknlLCkMMMmDDxneN5DSuPlkaHHuZIy7UYOaiAIt6fSFEvY7rcoIpL7rM9pAZjgjdfaKXKw/cNygOz91lKByJvJCHqfMhENP+03Bbib9YH0ThI7SLTU0Vc61hW+ioRulYkKQ8OyY/vB8cWlHHRL3Tb/jyhmz/J/GTUl/colEPW/erJVBIa7AqNNgWIUprAs4QQ3RBBp5pREMJPlt1cLuAwIDAQAB-----END PUBLIC KEY-----
      id: fraud-engine

  secret-key: AuthETransactNgView2021

spring:
  application:
    name: fraud-eagle-eye-manager-service
  security:
      user:
        password: password
  ## MailProperties
  mail:
    host: smtp.gmail.com
    port: 587
    username: ollysun@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: none

  redis:
    client-type: jedis
    host: 172.17.10.16
    #host: 127.0.0.1
    port: 6379
    database: 0
#    password: visionsvisions


  cloud:
    consul:
      host: http://consul.staging.etranzactng.net

  sleuth:
    enabled: true

  zipkin:
    baseUrl: http://172.17.10.83:9411
    sender:
      type: web

  datasource:
    username: eagleeye_user
    password: T@w!d2021
    url: jdbc:mysql://172.17.10.83:3306/eagle_eye?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=Africa/Lagos
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  authorisation-service:
    userAuthoriserUrl: http://localhost:9191/api/v1/users/authoriser
    roleAuthoriserUrl: http://localhost:9191api/v1/roles/authoriser
    roleIdsByPermissionNameUrl: http://localhost:9191/api/v1/roles/permissionroles

#  second-datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/authorisation_service?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=Africa/Lagos

  jackson:
    default-property-inclusion: NON_NULL
    mapper:
      accept-case-insensitive-properties: true


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092 #10.0.0.178:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  main:
    allow-bean-definition-overriding: true

management:
  server:
    port: 9190
  health:
    db.enabled: true
    show-details: ALWAYS
  endpoints:
    web.exposure.include: "*"

  metrics:
    export:
      prometheus:
        enabled: true

logging:
  file:
    name: logs/application.log
    max-history: 20
    max-size: 20MB
  level:
    org.apache.http: INFO
    org.springframework.cloud.sleuth: INFO
    org.springframework.web: INFO
    com.netflix.discovery.DiscoveryClient: INFO
    org.springframework.security: INFO
    org.hibernate: ERROR
    com.etz.fraudengine: INFO
    org.apache.kafka: WARN
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 5000
      circuitBreaker.errorThresholdPercentage: 60
      circuitBreaker.sleepWindowInMilliseconds: 20000
      circuitBreaker.requestVolumeThreshold: 10

